### ISSUE TITLE
Quickstart link needs update

### ISSUE THREAD

**Issue by hlovdal** [kre/Kinetic-Rules-Engine#102]
The quickstart link in https://github.com/kre/Kinetic-Rules-Engine/blob/master/README.md should be updated to https://picolabs.atlassian.net/wiki/spaces/docs/pages/19791878/Pico+Engine+Quickstart (as far as I can tell).

**Comment by windley** [comment]
Thanks. I've updated the README to point to the new engine generally and delete things that might make people think they could use this.

**Comment by windley** [comment]
Thanks. I've updated the README to point to the new engine and remove things that might make people think this one is still in operation.
