### ISSUE TITLE
pci:list_children unstable

### ISSUE THREAD

**Issue by earlyprogrammer** [kre/Kinetic-Rules-Engine#87]
before:
open some sort of note-taking program, you’ll be saving ECIs

devtools:
Create new account
Save the primary ECI (later referred to as {{primary}})
install rid b507377x0.dev

URLs (in order):

https://kibdev.kobj.net/sky/cloud/b507377x0/listChildren?_eci={{primary}}
Use this link liberally through the rest of this test to verify state.

https://kibdev.kobj.net/sky/cloud/b507377x0/newChild?_eci={{primary}}
Save ECI {{childA}}

https://kibdev.kobj.net/sky/cloud/b507377x0/newChild?_eci={{primary}}
Save ECI {{childB}}

https://kibdev.kobj.net/sky/cloud/b507377x0/newChild?_eci={{primary}}
Save ECI {{childC}}

https://kibdev.kobj.net/sky/cloud/b507377x0/listChildren?_eci={{primary}}
Confirm all three children are in the list

https://kibdev.kobj.net/sky/cloud/b507377x0/deletePico?_eci={{childB}}
No return specified in the documentation for pci:delete_cloud.
Any child may be deleted here (or multiple, but I suggest single deletion at first).

https://kibdev.kobj.net/sky/cloud/b507377x0/listChildren?_eci={{primary}}
This call will now always return null.  I have not found a way to get it to a good state.
Feel free to add/remove as many picos as desired to confirm this.

I used to get a KNS error on pci:list_children when empty or after the deletion, that is no longer the case, but the data still doesn't come through.

cleanup:
you may delete the account with
https://kibdev.kobj.net/sky/cloud/b507377x0/deletePico?_eci={{primary}}&cascade=1

**Comment by earlyprogrammer** [comment]
b507377x0 is
https://github.com/earlyprogrammer/glowing-octo-hipster/blob/master/picos.krl

**Comment by windley** [comment]
I believe this is fixed in 027b8cb. It passes tests now. Try and let me know.

**Comment by earlyprogrammer** [comment]
Confirmed,
Everything I've tried seems to be working.

**Comment by windley** [comment]
Good. Thanks for checking
