### ISSUE TITLE
pci:list_parent is incorrect

### ISSUE THREAD

**Issue by earlyprogrammer** [kre/Kinetic-Rules-Engine#88]
before:
open some sort of note-taking program, you’ll be saving ECIs

devtools:
Create new account
Save the primary ECI (later referred to as {{primary}})
install rid b507377x0.dev

URLs:

https://kibdev.kobj.net/sky/cloud/b507377x0/newChild?_eci={{primary}}
Save ECI {{child}}

https://kibdev.kobj.net/sky/cloud/b507377x0/newChild?_eci={{child}}
Save ECI {{grandchild}}

https://kibdev.kobj.net/sky/cloud/b507377x0/listParent?_eci={{primary}}
Note the result is null, as expected

https://kibdev.kobj.net/sky/cloud/b507377x0/listParent?_eci={{child}}
Note the result is {{child}}, but should be {{parent}}

https://kibdev.kobj.net/sky/cloud/b507377x0/listParent?_eci={{grandchild}}
Note the result is {{grandchild}}, but should be {{child}}

cleanup:
you may delete the account with
https://kibdev.kobj.net/sky/cloud/b507377x0/deletePico?_eci={{primary}}&cascade=1

**Comment by earlyprogrammer** [comment]
b507377x0 is
https://github.com/earlyprogrammer/glowing-octo-hipster/blob/master/picos.krl

**Comment by windley** [comment]
Thanks for the detailed notes on reproducing problem. Made it easy to find. 

Fixed in 04f583c
