### ISSUE TITLE
Empty Client List Error

### ISSUE THREAD

**Issue by earlyprogrammer** [kre/Kinetic-Rules-Engine#92]
This link wraps a call to pci:list_apps() on a pico with no registered clients.
KNS Error encountered

https://kibdev.kobj.net/sky/cloud/b507199x0.dev/showClients?_eci=F359FEF0-36F0-11E5-A752-BEE9E71C24E1

**Comment by windley** [comment]
Fixed in dd249de3774a1668a867dd62ddc01b96029466e4
